### ISSUE TITLE
remove myproxy dependency

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#17]
Would it make sense to pass delegated proxy to backend directly? Would remove extra firewall requirement and might even make login faster. 

proxy could either be passed with each call, or stored on backend and referred to by authentication token.

**Comment by makkus** [comment]
Hm, good point.

Not 100% sure about security implications.
One thing about myproxy is that you can restrict it to a certain 
retriever and you can revoke it. On the other hand, practically that 
doesn't make a difference because once the backend got hold of the proxy 
it can do anything it wants with it anyway.

We'd have to implement delegation of certificate to backend though, we 
can't just put it in the header or so. Proxies can never be sent to the 
backend directly (because of key that is contained within). So that 
would make client (and server) code more complicated and it's not 
username/password anymore.

Also, myproxy communication from client might not be necessary anymore 
later on, depending on how we are going to implement our user-database 
thingy.

If we do it, I'd suggest as an alternative, not as a replacement. 
Auth-code would need some refactoring, but that isn't necessarily a bad 
thing...
- Markus

**Comment by makkus** [comment]
I guess I close this? We would have to implement proxy delegation and I don't see that happening in the near future. Although it might be possible without too much effort (still some though) on the backend, now that auth is spring based, client side would probably still be quite difficult to implement. Also, it would have to be implemented for every client language we want to support in the future (esp. python)...

Re-open if you think it's necessary.
