### ISSUE TITLE
remove "cannot get user for session" exception

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#21]
Hard to monitor logs.

**Comment by makkus** [comment]
Hard to get rid of.

It's somewhere in JAX-WS, not sure where to catch it...

**Comment by makkus** [comment]
Too late for this milestone, move to next.

**Comment by makkus** [comment]
I agree this is annoying, but, to be honest, I'm not really sure whether we should spend time on that at the moment. The way we publish the soap interface might change in the near future because of some updates to the enunciate library we are using. 

Also, sooner or later we might really want to have a proper, working REST interface. Which could maybe replace the current SOAP one.

Can I close it and we live just with the verboseness? There are bigger fish to fry, I think...

**Comment by yuriyh** [comment]
removed it from milestone.  Lets leave it in github, for reference.

**Comment by makkus** [comment]
Log output is clean now.
